### ISSUE TITLE
Disable Sentry

### ISSUE THREAD

**Issue by rogatty** [wodac/wnl-customization#5]
Hi Wojciech! How do you feel about disabling Sentry before running your code? It's causing some errors, which spam our error reporting. We may miss some real issues because of that.

I found https://forum.sentry.io/t/disable-sentry-in-angular-application-at-runtime/8343/6:
```
__SENTRY__.hub.getClient().getOptions().enabled = false;
```
I ran it in the console and errors were no longer being sent to Sentry. Should work just fine if you put it near the start of the main script. It's a bit hacky but that's what custom extensions are about, right? 🙂 

Thanks!

**Comment by wodac** [comment]
Hi, I actually recently thought about it 😅 Sorry for spamming 😥
